[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
watch = ["src", "style", "../shared"]

[serve]
port = 8080

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = [
    "tailwindcss",
    "-i",
    "./style/input.css",
    "-o",
    "./style/output.css",
]

[[hooks]]
stage = "build"
command = "npx"
command_arguments = [
    "tailwindcss",
    "-i",
    "./style/input.css",
    "-o",
    "./dist/output.css",
]

[[hooks]]
stage = "build"
command = "cp"
command_arguments = [
    "vercel.json",
    "dist/vercel.json",
]
