[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "style"]

[serve]
port = 8080

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = [
    "tailwindcss",
    "-i",
    "./style/input.css",
    "-o",
    "./style/output.css",
]

[[hooks]]
stage = "build"
command = "npx"
command_arguments = [
    "tailwindcss",
    "-i",
    "./style/input.css",
    "-o",
    "./dist/output.css",
]
