# Crux dependency configuration for CI/CD
# This file controls how Crux is obtained in different environments

# Default configuration - uses official Crux repository
default:
  source: "git"
  repository: "redbadger/crux"
  ref: "main"
  path: "../crux"

# Development configuration - assumes local Crux
development:
  source: "local"
  path: "../crux"
  fallback:
    source: "git"
    repository: "redbadger/crux"
    ref: "main"

# CI/CD configuration - uses git checkout
ci:
  source: "git"
  repository: "redbadger/crux"
  ref: "main"
  path: "../crux"
  
# Alternative: Use a specific commit/tag if needed
# ci:
#   source: "git"
#   repository: "redbadger/crux"
#   ref: "v0.7.0"  # Use specific version
#   path: "../crux"

# Alternative: Use a fork if you have changes
# ci:
#   source: "git"
#   repository: "your-username/crux"
#   ref: "feature-branch"
#   path: "../crux"