name = "Practice App"
description = "A practice app to demonstrate Crux"
authors = ["Jon Yardley"]
repository = "https://github.com/jonyardley/practice_app"

[cores.shared]
source = "shared"
type_gen = "shared_types"
crux_version = "0.6.3"

[shells.web_dioxus]
template = "web-dioxus"
source = "web-dioxus"
cores = ["shared"]
