# Rust formatting configuration for Intrada project
# This ensures consistent formatting across all Rust code in the workspace
# Only stable rustfmt options are used

# Edition configuration
edition = "2021"

# Code style
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
reorder_imports = true

# Misc
remove_nested_parens = true
use_small_heuristics = "Default"