[application]
name = "practice-app"

[web.app]
title = "Practice App"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[web]

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
index_on_404 = true
