#!/usr/bin/env ruby
# frozen_string_literal: true

# add-live-activity-target.rb
#
# Adds the IntradaLiveActivity widget extension target to the Xcode
# project that `cargo tauri ios init` generated. Required because
# Tauri 2 / cargo-mobile2 only templates a single app target — Live
# Activities (#474) need a separate Widget Extension bundle to host
# the SwiftUI views Apple's WidgetKit framework renders.
#
# How it works:
#   1. Reads gen/apple/project.yml (xcodegen spec generated by Tauri).
#   2. Adds an `IntradaLiveActivity` target to that YAML pointing at the
#      Swift sources + Info.plist under crates/intrada-mobile/widget-extension/.
#   3. Wires the new target as an embedded dependency of the main app.
#   4. Re-runs `xcodegen generate` to rebuild the .xcodeproj from the
#      mutated YAML. xcodegen handles all the pbxproj UUID / file
#      reference juggling — we only deal with human-readable YAML.
#
# Idempotent: if the target is already present, the script reports and
# exits 0 without re-running xcodegen.
#
# When to run: once after `cargo tauri ios init`. The generated
# `gen/apple/` directory is gitignored, so re-running ios init wipes
# this addition — re-run the script if that happens.
#
# Spec: specs/live-activity-plugin.md

require 'pathname'
require 'yaml'

# ── Paths ─────────────────────────────────────────────────────────────
MOBILE_ROOT = Pathname.new(__dir__).parent.expand_path
GEN_DIR     = MOBILE_ROOT.join('src-tauri/gen/apple')
PROJECT_YML = GEN_DIR.join('project.yml')

WIDGET_EXTENSION_ROOT = MOBILE_ROOT.join('widget-extension')
SHARED_PACKAGE_ROOT   = MOBILE_ROOT.join('shared/IntradaActivityShared')

# Bundle ID convention: append `.LiveActivity` to the main app's bundle
# ID. Apple requires extension bundle IDs to be a child of the host
# app's bundle ID for App Store submission.
TARGET_NAME       = 'IntradaLiveActivity'
TARGET_BUNDLE_ID  = 'com.intrada.app.LiveActivity'

# Shared Swift package consumed by both this widget extension and the
# tauri-plugin-live-activity Swift target. Hosts the
# `IntradaActivityAttributes` type — the same identity must appear on
# both sides of the `Activity<T>` / `ActivityConfiguration<T>`
# boundary (Swift's type system enforces this).
SHARED_PACKAGE_NAME    = 'IntradaActivityShared'
SHARED_PACKAGE_PRODUCT = 'IntradaActivityShared'

# Live Activities first shipped in iOS 16.1. Bumping above the main
# app's deployment target (iOS 14.0 per project.yml) is fine — the
# extension just won't be loaded on older devices.
MIN_IOS_DEPLOYMENT = '16.1'

# ── Pre-flight ────────────────────────────────────────────────────────
unless PROJECT_YML.exist?
  abort <<~ERR
    ERROR: #{PROJECT_YML} not found.
    Run `cargo tauri ios init` from #{MOBILE_ROOT.join('src-tauri')} first.
  ERR
end

unless WIDGET_EXTENSION_ROOT.directory?
  abort <<~ERR
    ERROR: #{WIDGET_EXTENSION_ROOT} not found.
    The widget-extension/ directory is checked in — this script should be
    run from a clean checkout. If it's missing, your tree is broken.
  ERR
end

unless SHARED_PACKAGE_ROOT.directory?
  abort <<~ERR
    ERROR: #{SHARED_PACKAGE_ROOT} not found.
    The shared SwiftPM package (IntradaActivityShared) is checked in — this script
    should be run from a clean checkout. If it's missing, your tree is broken.
  ERR
end

unless system('which', 'xcodegen', out: File::NULL, err: File::NULL)
  abort <<~ERR
    ERROR: xcodegen not found on PATH.
    Tauri's iOS workflow depends on xcodegen — install with:
      brew install xcodegen
  ERR
end

# ── Load + check ──────────────────────────────────────────────────────
project = YAML.load_file(PROJECT_YML)

main_target_name = 'intrada-mobile_iOS'
unless project['targets']&.key?(main_target_name)
  abort "ERROR: expected main target '#{main_target_name}' in project.yml — Tauri may have changed the target name. Update this script."
end

# If the widget extension target is already present, the only thing left
# to (potentially) apply is the ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES fix
# below. Fall through and let the script idempotently ensure that
# setting is present, then re-run xcodegen if it changed anything.
target_already_present = project['targets'].key?(TARGET_NAME)
if target_already_present
  puts "✓ #{TARGET_NAME} target already present — checking build settings."
end

# ── Mutate ────────────────────────────────────────────────────────────
mutated = false

# Paths in project.yml are relative to gen/apple/. We need to express
# the path back up to crates/intrada-mobile/widget-extension/ and the
# shared SwiftPM package directory.
widget_rel = WIDGET_EXTENSION_ROOT.relative_path_from(GEN_DIR).to_s
shared_rel = SHARED_PACKAGE_ROOT.relative_path_from(GEN_DIR).to_s

unless target_already_present
# Declare the shared SwiftPM package at project scope so multiple
# targets can depend on it. xcodegen merges this with whatever existing
# `packages:` section Tauri's template has (currently empty).
project['packages'] ||= {}
project['packages'][SHARED_PACKAGE_NAME] = { 'path' => shared_rel }

project['targets'][TARGET_NAME] = {
  'type'       => 'app-extension',
  'platform'   => 'iOS',
  'sources'    => [
    { 'path' => "#{widget_rel}/Sources" }
  ],
  # Let xcodegen own the Info.plist generation — we declare the
  # extension-specific keys here and xcodegen merges them into a basic
  # plist at gen/apple/IntradaLiveActivity/Info.plist (gitignored).
  # Hand-shipping an Info.plist gets clobbered by xcodegen's defaults.
  'info'       => {
    'path'       => "#{TARGET_NAME}/Info.plist",
    'properties' => {
      'CFBundleDisplayName' => 'Intrada Live Activity',
      'CFBundleShortVersionString' => '0.1.0',
      'CFBundleVersion' => '0.1.0',
      'NSExtension' => {
        'NSExtensionPointIdentifier' => 'com.apple.widgetkit-extension',
      },
    },
  },
  'settings'   => {
    'base' => {
      'PRODUCT_NAME'                => TARGET_NAME,
      'PRODUCT_BUNDLE_IDENTIFIER'   => TARGET_BUNDLE_ID,
      'IPHONEOS_DEPLOYMENT_TARGET'  => MIN_IOS_DEPLOYMENT,
      'SWIFT_VERSION'               => '5.0',
      'CODE_SIGN_STYLE'             => 'Automatic',
      'DEVELOPMENT_TEAM'            => '9S5FG4LQAF',
      'SKIP_INSTALL'                => 'NO',
    },
  },
  'dependencies' => [
    { 'sdk' => 'WidgetKit.framework' },
    { 'sdk' => 'SwiftUI.framework' },
    { 'sdk' => 'ActivityKit.framework' },
    # Shared types (IntradaActivityAttributes) — declared in the
    # project-scope `packages:` section above. Same package is also
    # referenced by tauri-plugin-live-activity's Package.swift, so the
    # SAME type identity reaches both the widget extension and the
    # plugin's Activity<T>.request call.
    { 'package' => SHARED_PACKAGE_NAME, 'product' => SHARED_PACKAGE_PRODUCT },
  ],
}

# Add as embedded dependency on the main app so the extension ships
# inside the .app bundle.
main_target = project['targets'][main_target_name]
main_target['dependencies'] ||= []

# Skip if a dependency on this target already exists (defensive — earlier
# guard should have caught it, but cheap to double-check).
already_dep = main_target['dependencies'].any? { |d| d.is_a?(Hash) && d['target'] == TARGET_NAME }
unless already_dep
  main_target['dependencies'] << { 'target' => TARGET_NAME, 'embed' => true }
end

mutated = true
end # unless target_already_present

main_target = project['targets'][main_target_name]

# Force-embed the Swift standard libraries on the main app target.
#
# Why: before Phase C the main app was pure Rust — Xcode never ran the
# "Embed Swift Standard Libraries" build phase, because nothing in the
# main target linked Swift. Phase C adds a Swift app-extension dependency
# (IntradaLiveActivity) and pulls in the IntradaActivityShared SwiftPM
# product. That partially activates Swift toolchain behavior: Xcode copies
# the back-deployment shim libswift_Concurrency.dylib into Frameworks/,
# but without ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES, the
# swift-stdlib-tool pass that would copy libswiftCore.dylib (and friends)
# alongside it never runs.
#
# Result on device: dyld tries to resolve @rpath/libswiftCore.dylib for
# libswift_Concurrency.dylib at launch, fails, and halts the process
# before main runs. Symptom is "white screen then disappears" — launch
# storyboard renders, then SIGABRT from dyld with
# "Library not loaded: @rpath/libswiftCore.dylib".
#
# The simulator masks this — its dyld cache resolves Swift stdlib
# regardless of bundle contents — so the bug only shows up on device.
#
# Setting it on the main target tells Xcode to run the embed pass for
# the whole .app bundle. The widget extension nested inside picks up
# the same dylibs from the parent bundle's Frameworks/ via @rpath.
main_target['settings'] ||= {}
main_target['settings']['base'] ||= {}
if main_target['settings']['base']['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] != 'YES'
  main_target['settings']['base']['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
  mutated = true
  puts '✓ Set ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES on main app target.'
end

# ── Save ──────────────────────────────────────────────────────────────
unless mutated
  puts '✓ Nothing to do — project.yml already up to date.'
  exit 0
end

PROJECT_YML.write(project.to_yaml)
puts "✓ Wrote #{PROJECT_YML.relative_path_from(MOBILE_ROOT)}"

# ── Re-run xcodegen ───────────────────────────────────────────────────
puts '→ Re-running xcodegen to regenerate .xcodeproj…'
ok = Dir.chdir(GEN_DIR) do
  system('xcodegen', 'generate', '--no-env', '--spec', 'project.yml')
end

unless ok
  abort 'ERROR: xcodegen generate failed. Check the output above.'
end

puts "✓ Regenerated .xcodeproj. The widget extension target is ready."
puts ''
puts "Next: build the iOS app to verify the new target compiles:"
puts "  cd #{MOBILE_ROOT.join('src-tauri')} && cargo tauri ios build --target aarch64"
