services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: intrada
      POSTGRES_USER: intrada
      POSTGRES_PASSWORD: intrada
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
