version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: intrada_db
      POSTGRES_USER: intrada_user
      POSTGRES_PASSWORD: intrada_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U intrada_user -d intrada_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: