name: Intrada
packages:
  Shared:
    path: ../shared/Shared
  SharedTypes:
    path: ../shared_types/generated/swift/SharedTypes

options:
  bundleIdPrefix: com.jonyardley
targets:
  Intrada:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources: [Intrada]
    dependencies:
      - package: Shared
      - package: SharedTypes
    team: JYARDLEY
    info:
      path: Intrada/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
        CFBundleIconName: AppIcon
