name: Intrada
packages:
  Shared:
    path: ../shared/Shared
  SharedTypes:
    path: ../shared_types/generated/swift/SharedTypes

options:
  bundleIdPrefix: com.jonyardley
targets:
  Intrada:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources: 
      - Intrada
      - path: Intrada/GeneratedConfig.swift
        type: file
    resources: 
      - Intrada/Config.plist
    dependencies:
      - package: Shared
      - package: SharedTypes
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY[sdk=iphonesimulator*]: ""
        CODE_SIGNING_ALLOWED[sdk=iphonesimulator*]: NO
        CODE_SIGNING_REQUIRED[sdk=iphonesimulator*]: NO
    info:
      path: Intrada/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
        CFBundleIconName: AppIcon
