#!/usr/bin/env bash
# build-ios.sh — Cross-compile the shared crate for iOS and generate Swift bindings.
#
# Usage:
#   ./scripts/build-ios.sh          # Build for device + simulator, generate types
#   ./scripts/build-ios.sh --device  # Build for device only
#   ./scripts/build-ios.sh --sim     # Build for simulator only
#   ./scripts/build-ios.sh --types   # Generate Swift types only (no Rust build)
#
# Prerequisites:
#   - Rust iOS targets: rustup target add aarch64-apple-ios aarch64-apple-ios-sim
#   - Xcode + command line tools

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Output directories — inside the Xcode source root so XcodeGen picks them up
GENERATED_DIR="$ROOT_DIR/ios/Intrada/Generated"
BINDINGS_DIR="$GENERATED_DIR/UniFFI"

# Where facet typegen outputs the Swift package
TYPEGEN_OUTPUT="$ROOT_DIR/crates/shared_types/generated/swift/SharedTypes"

# Targets
DEVICE_TARGET="aarch64-apple-ios"
SIM_TARGET="aarch64-apple-ios-sim"

# Defaults
BUILD_DEVICE=true
BUILD_SIM=true
GENERATE_TYPES=true
PROFILE="release"

# Parse args
for arg in "$@"; do
    case $arg in
        --device)
            BUILD_SIM=false
            ;;
        --sim)
            BUILD_DEVICE=false
            ;;
        --types)
            BUILD_DEVICE=false
            BUILD_SIM=false
            ;;
        --debug)
            PROFILE="dev"
            ;;
        --help)
            echo "Usage: $0 [--device|--sim|--types] [--debug]"
            exit 0
            ;;
    esac
done

PROFILE_DIR="release"
PROFILE_FLAG="--release"
if [ "$PROFILE" = "dev" ]; then
    PROFILE_DIR="debug"
    PROFILE_FLAG=""
fi

echo "=== Intrada iOS Build ==="
echo "  Root:    $ROOT_DIR"
echo "  Profile: $PROFILE"
echo ""

# ───────────────────────────────────────────────────
# Step 1: Cross-compile shared crate for iOS targets
# ───────────────────────────────────────────────────

if [ "$BUILD_DEVICE" = true ]; then
    echo "→ Building for device ($DEVICE_TARGET)..."
    cargo build -p shared --features uniffi $PROFILE_FLAG --target "$DEVICE_TARGET"
    echo "  ✓ Device library: target/$DEVICE_TARGET/$PROFILE_DIR/libshared.a"
fi

if [ "$BUILD_SIM" = true ]; then
    echo "→ Building for simulator ($SIM_TARGET)..."
    cargo build -p shared --features uniffi $PROFILE_FLAG --target "$SIM_TARGET"
    echo "  ✓ Simulator library: target/$SIM_TARGET/$PROFILE_DIR/libshared.a"
fi

# ───────────────────────────────────────────────────
# Step 2: Generate Swift type bindings via facet typegen
# ───────────────────────────────────────────────────

if [ "$GENERATE_TYPES" = true ]; then
    echo ""
    echo "→ Generating Swift type bindings (facet typegen)..."

    # Build shared_types crate — its build.rs runs TypeRegistry to generate Swift
    cargo build -p shared_types
    echo "  ✓ SharedTypes generated: $TYPEGEN_OUTPUT"

    # Remove old hand-written files (replaced by fully automated typegen)
    for old_file in "$GENERATED_DIR/SharedTypes.swift" "$GENERATED_DIR/CodableExtensions.swift"; do
        if [ -f "$old_file" ]; then
            rm "$old_file"
            echo "  ✓ Removed old $(basename "$old_file")"
        fi
    done

    # ─── 2a. Copy generated SharedTypes into the iOS project ───

    mkdir -p "$GENERATED_DIR/SharedTypes"
    cp -R "$TYPEGEN_OUTPUT/Sources/SharedTypes/"*.swift "$GENERATED_DIR/SharedTypes/"

    # Strip `import Serde` — generated as a separate module but we compile in a single target
    sed -i '' '/^import Serde$/d' "$GENERATED_DIR/SharedTypes/"*.swift

    # Prepend "DO NOT EDIT" header to generated files
    for f in "$GENERATED_DIR/SharedTypes/"*.swift; do
        sed -i '' '1s;^;// ⚠️  AUTO-GENERATED by `just typegen` — DO NOT EDIT manually.\n// Changes will be overwritten on next `just typegen` or `build-ios.sh` run.\n\n;' "$f"
    done

    echo "  ✓ Copied to: $GENERATED_DIR/SharedTypes/ (stripped import Serde)"

    # ─── 2b. Append Codable + Sendable to SharedTypes.swift ───
    #
    # Swift 6 requires auto-synthesised Codable to be in the SAME file as the
    # struct definition. Sendable too, because @Indirect blocks auto-synthesis.
    # These empty conformances trigger the compiler's auto-synthesis.

    cat >> "$GENERATED_DIR/SharedTypes/SharedTypes.swift" << 'SAMEFILE_EXTENSIONS'

// MARK: - Codable (auto-injected by build-ios.sh for REST API JSON serialisation)
//
// Swift 6 requires these to be in the same file as the struct definition
// for auto-synthesis to work through the @Indirect property wrapper.

extension Item: Codable {}
extension Tempo: Codable {}
extension PracticeSession: Codable {}
extension SetlistEntry: Codable {}
extension Routine: Codable {}
extension RoutineEntry: Codable {}
extension Goal: Codable {}
extension ActiveSession: Codable {}

// MARK: - Sendable (auto-injected by build-ios.sh for Swift 6 strict concurrency)
//
// @Indirect is a value-type enum wrapping value types — safe to send across
// concurrency boundaries. @unchecked because Swift can't auto-synthesise
// through the property wrapper.

extension Item: @unchecked Sendable {}
extension Tempo: @unchecked Sendable {}
extension PracticeSession: @unchecked Sendable {}
extension SetlistEntry: @unchecked Sendable {}
extension Routine: @unchecked Sendable {}
extension RoutineEntry: @unchecked Sendable {}
extension Goal: @unchecked Sendable {}
extension ActiveSession: @unchecked Sendable {}
SAMEFILE_EXTENSIONS
    echo "  ✓ Appended Codable + Sendable conformances to SharedTypes.swift"

    # ─── 2c. Generate TypeExtensions.swift ───
    #
    # Everything that CAN live in a separate file (explicit protocol implementations):
    #   - Indirect<T> Codable/Sendable (property wrapper used by all generated structs)
    #   - Enum Codable (explicit implementations matching Rust serde attributes)
    #   - JSON coders with snake_case key strategy for the REST API
    #
    # This replaces the old hand-maintained CodableExtensions.swift.

    cat > "$GENERATED_DIR/SharedTypes/TypeExtensions.swift" << 'TYPE_EXTENSIONS'
// ⚠️  AUTO-GENERATED by build-ios.sh — DO NOT EDIT manually.
// Changes will be overwritten on next `just typegen` or `build-ios.sh` run.
//
// Adds JSON Codable conformances for auto-generated types that cross the
// REST API boundary. Facet typegen generates BCS (Binary Canonical Serialization)
// for the Crux FFI bridge; this file adds standard Swift Codable for JSON.
//
// Enum Codable implementations match the Rust serde attributes exactly.
// When Rust domain enums change, re-run `just typegen` to regenerate.

import Foundation

// MARK: - Indirect Property Wrapper Extensions

// Auto-generated structs use @Indirect for all properties. These transparent
// extensions let Swift's auto-synthesised Codable encode/decode the wrapped
// value, and Sendable lets the structs cross concurrency boundaries (Swift 6).

extension Indirect: @unchecked Sendable where T: Sendable {}

extension Indirect: Encodable where T: Encodable {
    public func encode(to encoder: Encoder) throws {
        try wrappedValue.encode(to: encoder)
    }
}

extension Indirect: Decodable where T: Decodable {
    public init(from decoder: Decoder) throws {
        self.init(wrappedValue: try T(from: decoder))
    }
}

// MARK: - JSON Coders for REST API

extension JSONDecoder {
    /// Decoder for the Intrada REST API.
    ///
    /// Uses `.convertFromSnakeCase` to match Rust's default serde field naming.
    /// Date fields are String in the auto-generated types, so no custom date
    /// strategy is needed.
    static let api: JSONDecoder = {
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return decoder
    }()
}

extension JSONEncoder {
    /// Encoder for the Intrada REST API.
    ///
    /// Uses `.convertToSnakeCase` to match Rust's default serde field naming.
    static let api: JSONEncoder = {
        let encoder = JSONEncoder()
        encoder.keyEncodingStrategy = .convertToSnakeCase
        return encoder
    }()
}

// MARK: - Enum Codable (matching Rust serde formats)

// ItemKind — Rust: #[serde(rename_all = "lowercase")]
// JSON: "piece", "exercise"
extension ItemKind: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(String.self)
        switch raw {
        case "piece": self = .piece
        case "exercise": self = .exercise
        default:
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Unknown ItemKind: \(raw)"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .piece: try container.encode("piece")
        case .exercise: try container.encode("exercise")
        }
    }
}

// GoalStatus — Rust: #[serde(rename_all = "snake_case")]
// JSON: "active", "completed", "archived"
extension GoalStatus: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(String.self)
        switch raw {
        case "active": self = .active
        case "completed": self = .completed
        case "archived": self = .archived
        default:
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Unknown GoalStatus: \(raw)"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .active: try container.encode("active")
        case .completed: try container.encode("completed")
        case .archived: try container.encode("archived")
        }
    }
}

// GoalKind — Rust: #[serde(rename_all = "snake_case", tag = "type")]
// JSON (internally tagged): {"type": "session_frequency", "target_days_per_week": 5}
extension GoalKind: Codable {
    private enum CodingKeys: String, CodingKey {
        case type
        case targetDaysPerWeek
        case targetMinutesPerWeek
        case itemId
        case targetScore
        case description
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)
        switch type {
        case "session_frequency":
            let v = try container.decode(UInt8.self, forKey: .targetDaysPerWeek)
            self = .sessionFrequency(targetDaysPerWeek: v)
        case "practice_time":
            let v = try container.decode(UInt32.self, forKey: .targetMinutesPerWeek)
            self = .practiceTime(targetMinutesPerWeek: v)
        case "item_mastery":
            let id = try container.decode(String.self, forKey: .itemId)
            let score = try container.decode(UInt8.self, forKey: .targetScore)
            self = .itemMastery(itemId: id, targetScore: score)
        case "milestone":
            let desc = try container.decode(String.self, forKey: .description)
            self = .milestone(description: desc)
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .type,
                in: container,
                debugDescription: "Unknown GoalKind type: \(type)"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .sessionFrequency(let targetDaysPerWeek):
            try container.encode("session_frequency", forKey: .type)
            try container.encode(targetDaysPerWeek, forKey: .targetDaysPerWeek)
        case .practiceTime(let targetMinutesPerWeek):
            try container.encode("practice_time", forKey: .type)
            try container.encode(targetMinutesPerWeek, forKey: .targetMinutesPerWeek)
        case .itemMastery(let itemId, let targetScore):
            try container.encode("item_mastery", forKey: .type)
            try container.encode(itemId, forKey: .itemId)
            try container.encode(targetScore, forKey: .targetScore)
        case .milestone(let description):
            try container.encode("milestone", forKey: .type)
            try container.encode(description, forKey: .description)
        }
    }
}

// CompletionStatus — Rust: no rename (default externally tagged)
// JSON: "Completed", "EndedEarly"
extension CompletionStatus: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(String.self)
        switch raw {
        case "Completed": self = .completed
        case "EndedEarly": self = .endedEarly
        default:
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Unknown CompletionStatus: \(raw)"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .completed: try container.encode("Completed")
        case .endedEarly: try container.encode("EndedEarly")
        }
    }
}

// EntryStatus — Rust: no rename (default externally tagged)
// JSON: "Completed", "Skipped", "NotAttempted"
extension EntryStatus: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(String.self)
        switch raw {
        case "Completed": self = .completed
        case "Skipped": self = .skipped
        case "NotAttempted": self = .notAttempted
        default:
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Unknown EntryStatus: \(raw)"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .completed: try container.encode("Completed")
        case .skipped: try container.encode("Skipped")
        case .notAttempted: try container.encode("NotAttempted")
        }
    }
}

// RepAction — Rust: #[serde_repr] #[repr(i8)]
// JSON: -1 (Missed), 1 (Success) — serialised as integers
extension RepAction: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(Int8.self)
        switch raw {
        case -1: self = .missed
        case 1: self = .success
        default:
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Unknown RepAction: \(raw)"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .missed: try container.encode(Int8(-1))
        case .success: try container.encode(Int8(1))
        }
    }
}
TYPE_EXTENSIONS
    echo "  ✓ Generated TypeExtensions.swift (Indirect, enum Codable, JSON coders)"

    # ─── 2d. Copy Serde runtime (BCS serialization helpers) ───

    mkdir -p "$GENERATED_DIR/Serde"
    cp -R "$TYPEGEN_OUTPUT/Sources/Serde/"*.swift "$GENERATED_DIR/Serde/"

    # Prepend "DO NOT EDIT" header to Serde files
    for f in "$GENERATED_DIR/Serde/"*.swift; do
        sed -i '' '1s;^;// ⚠️  AUTO-GENERATED by `just typegen` — DO NOT EDIT manually.\n\n;' "$f"
    done

    echo "  ✓ Serde runtime: $GENERATED_DIR/Serde/"

    # ─── 2e. Generate UniFFI bindings (CoreFFI + CoreJson interface) ───

    mkdir -p "$BINDINGS_DIR"

    # Build uniffi-bindgen and generate Swift bindings
    if [ "$BUILD_SIM" = true ]; then
        LIB_PATH="$ROOT_DIR/target/$SIM_TARGET/$PROFILE_DIR/libshared.dylib"
    elif [ "$BUILD_DEVICE" = true ]; then
        LIB_PATH="$ROOT_DIR/target/$DEVICE_TARGET/$PROFILE_DIR/libshared.dylib"
    else
        # Types-only mode — build for host to generate bindings
        cargo build -p shared --features uniffi
        LIB_PATH="$ROOT_DIR/target/$PROFILE_DIR/libshared.dylib"
    fi

    cargo run -p shared --features uniffi-bindgen -- \
        generate --library "$LIB_PATH" \
        --language swift \
        --out-dir "$BINDINGS_DIR" 2>/dev/null || {
        echo "  ⚠ UniFFI binding generation skipped (library not available as dylib)"
        echo "  → Swift bindings will be generated during Xcode build"
    }

    echo "  ✓ UniFFI bindings: $BINDINGS_DIR"
fi

# ───────────────────────────────────────────────────
# Step 3: Summary
# ───────────────────────────────────────────────────

echo ""
echo "=== Build Complete ==="

if [ "$BUILD_DEVICE" = true ]; then
    DEVICE_LIB="$ROOT_DIR/target/$DEVICE_TARGET/$PROFILE_DIR/libshared.a"
    if [ -f "$DEVICE_LIB" ]; then
        echo "  Device lib:  $DEVICE_LIB ($(du -h "$DEVICE_LIB" | cut -f1))"
    fi
fi

if [ "$BUILD_SIM" = true ]; then
    SIM_LIB="$ROOT_DIR/target/$SIM_TARGET/$PROFILE_DIR/libshared.a"
    if [ -f "$SIM_LIB" ]; then
        echo "  Sim lib:     $SIM_LIB ($(du -h "$SIM_LIB" | cut -f1))"
    fi
fi

echo "  Types:       $GENERATED_DIR/SharedTypes/"
echo "  Serde:       $GENERATED_DIR/Serde/"
echo "  Bindings:    $BINDINGS_DIR"
echo ""
echo "Next: Open ios/Intrada.xcodeproj in Xcode or run 'xcodegen' to regenerate the project."
