#!/usr/bin/env bash
# Rebuild docs/status.md from GitHub. The issues are the source of truth
# (CLAUDE.md), so what's in flight is derivable and was previously copied by
# hand into a file every concurrent branch then collided on.

set -euo pipefail

repo="jonyardley/intrada"
out="docs/status.md"

for tool in gh jq; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "❌ $tool is required" >&2
    exit 1
  }
done

open_prs=$(gh pr list --repo "$repo" --state open --limit 50 \
  --json number,title,isDraft,updatedAt,headRefName,closingIssuesReferences)
merged_prs=$(gh pr list --repo "$repo" --state merged --limit 15 \
  --json number,title,mergedAt)
claimed=$(gh issue list --repo "$repo" --label in-flight --state open --limit 50 \
  --json number,title,updatedAt)

# A PR names its issue either through a closing keyword or, by this repo's title
# convention, as a trailing "(#N)".
# `capture` yields nothing rather than null when it does not match, which would
# drop the whole row, so it is defaulted before the field is read.
pr_lines=$(printf '%s' "$open_prs" | jq -r '
  sort_by(.updatedAt) | reverse | .[] |
  (.closingIssuesReferences[0].number
   // ((.title | capture("#(?<n>[0-9]+)\\)\\s*$") // null)
       | if . then (.n | tonumber) else null end)) as $issue |
  "- [#\(.number)](https://github.com/jonyardley/intrada/pull/\(.number)) — \(.title)"
  + (if .isDraft then " *(draft)*" else "" end)
  + (if $issue then " — issue #\($issue)" else "" end)
  + "\n  `\(.headRefName)`, last touched \(.updatedAt | split("T")[0])"
')

claimed_lines=$(printf '%s\n%s' "$claimed" "$open_prs" | jq -rs '
  .[0] as $issues | .[1] as $prs |
  ($prs | map(
     (.closingIssuesReferences[].number),
     ((.title | capture("#(?<n>[0-9]+)\\)\\s*$") // null)
      | if . then (.n | tonumber) else empty end)
   )) as $covered |
  $issues | sort_by(.updatedAt) | reverse | .[] |
  select([.number] | inside($covered) | not) |
  "- [#\(.number)](https://github.com/jonyardley/intrada/issues/\(.number)) — \(.title)
  claimed, no PR open yet (last touched \(.updatedAt | split("T")[0]))"
')

landed_lines=$(printf '%s' "$merged_prs" | jq -r '
  .[] |
  "- [#\(.number)](https://github.com/jonyardley/intrada/pull/\(.number)) — \(.title) *(merged \(.mergedAt | split("T")[0]))*"
')

{
  cat <<'HEAD'
# Status — what's in flight now

> **Generated. Do not edit this file by hand.** Run `just status` to rebuild it.
>
> Everything below is read from GitHub, which is the source of truth: an open
> PR is the live claim on an issue, and the `in-flight` label is the claim
> before a PR exists (CLAUDE.md → Always). This file used to be written by hand
> in every PR, which meant every concurrent branch edited the same lines.
>
> Direction and phases live in [`roadmap.md`](roadmap.md); the *why* behind any
> one item lives in its issue and its spec under [`../specs/`](../specs/). The
> scope and timing detail is on the
> [project board](https://github.com/users/jonyardley/projects/2).

HEAD
  echo "_Rebuilt $(date -u +%Y-%m-%d) from GitHub._"
  echo
  echo "## In flight"
  echo
  if [ -n "$pr_lines" ]; then echo "$pr_lines"; else echo "_Nothing open._"; fi
  echo
  echo "## Claimed, no PR yet"
  echo
  echo "_An issue here is either genuinely being worked on without a PR yet, or"
  echo "its \`in-flight\` label outlived the PR that closed it._"
  echo
  if [ -n "$claimed_lines" ]; then echo "$claimed_lines"; else echo "_Nothing claimed._"; fi
  echo
  echo "## Recently landed"
  echo
  echo "$landed_lines"
} > "$out"

echo "✓ $out rebuilt"
