// The `#[effect]` macro generates an enum with large variant size differences
// (Request<AppEffect> vs Request<RenderOperation>); we can't Box through the macro.
#![allow(clippy::large_enum_variant)]

use crux_core::capability::Operation;
use crux_core::macros::effect;
use crux_core::render::RenderOperation;
use crux_core::{App, Command};
use serde::{Deserialize, Serialize};

use crate::analytics::compute_analytics;
use crate::domain::goal::{handle_goal_event, Goal, GoalEvent, GoalKind, GoalStatus};
use crate::domain::item::{handle_item_event, Item, ItemEvent, ItemKind};
use crate::domain::routine::{handle_routine_event, Routine, RoutineEvent};
use crate::domain::session::{
    handle_session_event, ActiveSession, PracticeSession, SessionEvent, SessionStatus,
};
use crate::domain::types::ListQuery;
use crate::model::{
    build_active_session_view, build_summary_view, entry_to_view, session_to_view,
    BuildingSetlistView, GoalProgress, GoalView, ItemPracticeSummary, LibraryItemView, Model,
    ViewModel,
};

/// Root Crux application for the music practice library.
#[derive(Default)]
pub struct Intrada;

/// All events the application can process.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub enum Event {
    Item(ItemEvent),
    Session(SessionEvent),
    Routine(RoutineEvent),
    Goal(GoalEvent),
    DataLoaded { items: Vec<Item> },
    SessionsLoaded { sessions: Vec<PracticeSession> },
    RoutinesLoaded { routines: Vec<Routine> },
    GoalsLoaded { goals: Vec<Goal> },
    LoadFailed(String),
    ClearError,
    SetQuery(Option<ListQuery>),
}

/// Side effects the core requests from shells.
///
/// The `#[effect(typegen)]` attribute macro from `crux_core` generates:
/// - An `EffectFfi` enum for cross-language serialisation (iOS/Android FFI)
/// - `From<Request<Op>>` impls for each variant
/// - `impl crux_core::Effect` and `impl crux_core::EffectFFI`
/// - `impl Export` for type generation (Swift/Kotlin/TypeScript types)
///
/// Source variants hold **operation types** (e.g. `RenderOperation`);
/// the macro wraps each in `Request<Op>` in the compiled enum.
#[effect(typegen)]
pub enum Effect {
    Render(RenderOperation),
    App(AppEffect),
}

/// Side-effect operations handled by the shell (HTTP API calls, localStorage).
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub enum AppEffect {
    LoadAll,
    SaveItem(Item),
    UpdateItem(Item),
    DeleteItem { id: String },
    LoadSessions,
    SavePracticeSession(PracticeSession),
    DeletePracticeSession { id: String },
    SaveSessionInProgress(ActiveSession),
    ClearSessionInProgress,
    SaveRoutine(Routine),
    UpdateRoutine(Routine),
    DeleteRoutine { id: String },
    SaveGoal(Goal),
    UpdateGoal(Goal),
    DeleteGoal { id: String },
    LoadGoals,
}

impl Operation for AppEffect {
    type Output = ();
}

// Note: `impl crux_core::Effect`, `impl crux_core::EffectFFI`, and
// `From<Request<Op>>` impls are generated by the `#[effect(typegen)]` macro.

impl App for Intrada {
    type Event = Event;
    type Model = Model;
    type ViewModel = ViewModel;
    type Effect = Effect;

    fn update(
        &self,
        event: Self::Event,
        model: &mut Self::Model,
    ) -> Command<Self::Effect, Self::Event> {
        match event {
            Event::Item(item_event) => handle_item_event(item_event, model),
            Event::Session(session_event) => handle_session_event(session_event, model),
            Event::Routine(routine_event) => handle_routine_event(routine_event, model),
            Event::Goal(goal_event) => handle_goal_event(goal_event, model),
            Event::DataLoaded { items } => {
                model.items = items;
                model.last_error = None;
                crux_core::render::render()
            }
            Event::SessionsLoaded { sessions } => {
                model.sessions = sessions;
                model.practice_summaries = build_practice_summaries(&model.sessions);
                crux_core::render::render()
            }
            Event::RoutinesLoaded { routines } => {
                model.routines = routines;
                crux_core::render::render()
            }
            Event::GoalsLoaded { goals } => {
                model.goals = goals;
                model.last_error = None;
                crux_core::render::render()
            }
            Event::LoadFailed(msg) => {
                model.last_error = Some(msg);
                crux_core::render::render()
            }
            Event::ClearError => {
                model.last_error = None;
                crux_core::render::render()
            }
            Event::SetQuery(query) => {
                model.active_query = query;
                crux_core::render::render()
            }
        }
    }

    fn view(&self, model: &Self::Model) -> Self::ViewModel {
        let mut items: Vec<LibraryItemView> = Vec::new();

        for item in &model.items {
            let practice = model.practice_summaries.get(&item.id).cloned();
            let subtitle = match item.kind {
                ItemKind::Piece => item.composer.clone().unwrap_or_default(),
                ItemKind::Exercise => item
                    .category
                    .clone()
                    .or_else(|| item.composer.clone())
                    .unwrap_or_default(),
            };
            let latest_achieved_tempo = practice.as_ref().and_then(|p| p.latest_tempo);
            items.push(LibraryItemView {
                id: item.id.clone(),
                item_type: item.kind.to_string(),
                title: item.title.clone(),
                subtitle,
                category: item.category.clone(),
                key: item.key.clone(),
                tempo: item
                    .tempo
                    .as_ref()
                    .map(|t| t.format_display())
                    .filter(|s| !s.is_empty()),
                notes: item.notes.clone(),
                tags: item.tags.clone(),
                created_at: item.created_at.to_rfc3339(),
                updated_at: item.updated_at.to_rfc3339(),
                practice,
                latest_achieved_tempo,
            });
        }

        // Apply active query filter
        if let Some(ref query) = model.active_query {
            items = apply_query_filter(items, query);
        }

        // Sort by created_at descending (newest first)
        items.sort_by(|a, b| b.created_at.cmp(&a.created_at));

        // Build completed session views sorted newest-first
        let mut sessions: Vec<_> = model.sessions.iter().map(session_to_view).collect();
        sessions.sort_by(|a, b| b.finished_at.cmp(&a.finished_at));

        // Build active session / building / summary views from session_status
        let (active_session, building_setlist, summary) = match &model.session_status {
            SessionStatus::Idle => (None, None, None),
            SessionStatus::Building(building) => {
                let entries: Vec<_> = building.entries.iter().map(entry_to_view).collect();
                let item_count = entries.len();
                (
                    None,
                    Some(BuildingSetlistView {
                        entries,
                        item_count,
                        session_intention: building.session_intention.clone(),
                    }),
                    None,
                )
            }
            SessionStatus::Active(active) => (Some(build_active_session_view(active)), None, None),
            SessionStatus::Summary(summary_session) => {
                (None, None, Some(build_summary_view(summary_session)))
            }
        };

        let session_status = match &model.session_status {
            SessionStatus::Idle => "idle".to_string(),
            SessionStatus::Building(_) => "building".to_string(),
            SessionStatus::Active(_) => "active".to_string(),
            SessionStatus::Summary(_) => "summary".to_string(),
        };

        // Compute analytics from session data.
        // Note: Uses Utc::now() which makes view() impure. This is a pragmatic
        // tradeoff — the date only changes once/day and caching analytics in the
        // Model would require plumbing a clock through the event system. All
        // computation functions accept `today` as a parameter for testability.
        let analytics = if model.sessions.is_empty() {
            None
        } else {
            let today = chrono::Utc::now().date_naive();
            Some(compute_analytics(&model.sessions, &model.items, today))
        };

        // Build routine views
        let routines = model
            .routines
            .iter()
            .map(|r| {
                use crate::model::{RoutineEntryView, RoutineView};
                RoutineView {
                    id: r.id.clone(),
                    name: r.name.clone(),
                    entry_count: r.entries.len(),
                    entries: r
                        .entries
                        .iter()
                        .map(|e| RoutineEntryView {
                            id: e.id.clone(),
                            item_id: e.item_id.clone(),
                            item_title: e.item_title.clone(),
                            item_type: e.item_type.clone(),
                            position: e.position,
                        })
                        .collect(),
                }
            })
            .collect();

        // Build goal views with computed progress
        let today = chrono::Utc::now();
        let goal_progress_map = compute_goal_progress(
            &model.goals,
            &model.sessions,
            &model.practice_summaries,
            today,
        );

        let goals: Vec<GoalView> = model
            .goals
            .iter()
            .map(|g| {
                let (kind_label, kind_type) = goal_kind_label(&g.kind);
                let (item_id, item_title) = match &g.kind {
                    GoalKind::ItemMastery { item_id, .. } => {
                        let title = model
                            .items
                            .iter()
                            .find(|i| i.id == *item_id)
                            .map(|i| i.title.clone());
                        (Some(item_id.clone()), title)
                    }
                    _ => (None, None),
                };
                let progress = if g.status == GoalStatus::Active {
                    goal_progress_map.get(&g.id).cloned()
                } else {
                    None
                };
                GoalView {
                    id: g.id.clone(),
                    title: g.title.clone(),
                    kind_label,
                    kind_type,
                    status: match g.status {
                        GoalStatus::Active => "active".to_string(),
                        GoalStatus::Completed => "completed".to_string(),
                        GoalStatus::Archived => "archived".to_string(),
                    },
                    progress,
                    deadline: g.deadline.map(|d| d.to_rfc3339()),
                    created_at: g.created_at.to_rfc3339(),
                    completed_at: g.completed_at.map(|d| d.to_rfc3339()),
                    item_id,
                    item_title,
                }
            })
            .collect();

        ViewModel {
            items,
            sessions,
            active_session,
            building_setlist,
            summary,
            session_status,
            error: model.last_error.clone(),
            analytics,
            routines,
            goals,
        }
    }
}

/// Build practice summaries for all items in a single pass over sessions.
///
/// Returns a map keyed by item_id. Called once when sessions change,
/// replacing the old per-item O(M×E) scan that ran on every render.
pub(crate) fn build_practice_summaries(
    sessions: &[PracticeSession],
) -> std::collections::HashMap<String, ItemPracticeSummary> {
    use crate::model::{ScoreHistoryEntry, TempoHistoryEntry};
    use std::collections::HashMap;

    let mut acc: HashMap<String, (usize, u64, Vec<ScoreHistoryEntry>, Vec<TempoHistoryEntry>)> =
        HashMap::new();

    for session in sessions {
        for entry in &session.entries {
            let record = acc
                .entry(entry.item_id.clone())
                .or_insert_with(|| (0, 0, Vec::new(), Vec::new()));
            record.0 += 1;
            record.1 += entry.duration_secs;

            if let Some(score) = entry.score {
                record.2.push(ScoreHistoryEntry {
                    session_date: session.started_at.to_rfc3339(),
                    score,
                    session_id: session.id.clone(),
                });
            }

            if let Some(tempo) = entry.achieved_tempo {
                record.3.push(TempoHistoryEntry {
                    session_date: session.started_at.to_rfc3339(),
                    tempo,
                    session_id: session.id.clone(),
                });
            }
        }
    }

    acc.into_iter()
        .map(
            |(item_id, (session_count, total_secs, mut score_history, mut tempo_history))| {
                score_history.sort_by(|a, b| b.session_date.cmp(&a.session_date));
                let latest_score = score_history.first().map(|e| e.score);

                tempo_history.sort_by(|a, b| b.session_date.cmp(&a.session_date));
                let latest_tempo = tempo_history.first().map(|e| e.tempo);

                (
                    item_id,
                    ItemPracticeSummary {
                        session_count,
                        total_minutes: (total_secs / 60) as u32,
                        latest_score,
                        score_history,
                        latest_tempo,
                        tempo_history,
                    },
                )
            },
        )
        .collect()
}

/// Compute progress for all active goals. Pure function — `now` param for testability.
///
/// - **SessionFrequency**: count distinct days with sessions in current ISO week
/// - **PracticeTime**: sum session durations in current ISO week (minutes)
/// - **ItemMastery**: latest_score from practice_summaries
/// - **Milestone**: 0% unless completed (handled in view builder)
pub(crate) fn compute_goal_progress(
    goals: &[Goal],
    sessions: &[PracticeSession],
    practice_summaries: &std::collections::HashMap<String, ItemPracticeSummary>,
    now: chrono::DateTime<chrono::Utc>,
) -> std::collections::HashMap<String, GoalProgress> {
    use chrono::{Datelike, NaiveDate};
    use std::collections::{HashMap, HashSet};

    let today = now.date_naive();

    // Pre-compute ISO week boundaries (Monday 00:00 .. Sunday 23:59)
    let iso_week = today.iso_week();
    let week_start =
        NaiveDate::from_isoywd_opt(iso_week.year(), iso_week.week(), chrono::Weekday::Mon)
            .expect("valid ISO week start");
    let week_end = week_start + chrono::Duration::days(7);

    // Collect per-week session data (only compute once for all goals)
    let mut week_days: HashSet<NaiveDate> = HashSet::new();
    let mut week_minutes: u64 = 0;

    for session in sessions {
        let session_date = session.started_at.date_naive();
        if session_date >= week_start && session_date < week_end {
            week_days.insert(session_date);
            week_minutes += session.total_duration_secs / 60;
        }
    }

    let mut progress_map: HashMap<String, GoalProgress> = HashMap::new();

    for goal in goals {
        if goal.status != GoalStatus::Active {
            continue;
        }

        let progress = match &goal.kind {
            GoalKind::SessionFrequency {
                target_days_per_week,
            } => {
                let current = week_days.len() as f64;
                let target = *target_days_per_week as f64;
                let pct = (current / target * 100.0).min(100.0);
                let days = week_days.len();
                let display_text = if days == 0 {
                    "Start your first session this week!".to_string()
                } else {
                    format!(
                        "{days} of {target_days_per_week} days — {}",
                        frequency_encouragement(pct)
                    )
                };
                GoalProgress {
                    current_value: current,
                    target_value: target,
                    percentage: pct,
                    display_text,
                }
            }
            GoalKind::PracticeTime {
                target_minutes_per_week,
            } => {
                let current = week_minutes as f64;
                let target = *target_minutes_per_week as f64;
                let pct = (current / target * 100.0).min(100.0);
                let display_text = if week_minutes == 0 {
                    "Start your first session this week!".to_string()
                } else {
                    format!(
                        "{week_minutes} of {target_minutes_per_week} min — {}",
                        time_encouragement(pct)
                    )
                };
                GoalProgress {
                    current_value: current,
                    target_value: target,
                    percentage: pct,
                    display_text,
                }
            }
            GoalKind::ItemMastery {
                item_id,
                target_score,
            } => {
                let current_score = practice_summaries
                    .get(item_id)
                    .and_then(|s| s.latest_score)
                    .unwrap_or(0);
                let current = current_score as f64;
                let target = *target_score as f64;
                let pct = (current / target * 100.0).min(100.0);
                let display_text = if current_score == 0 {
                    "No score recorded yet — practise this item to start tracking".to_string()
                } else {
                    format!(
                        "Score {current_score} of {target_score} — {}",
                        mastery_encouragement(pct)
                    )
                };
                GoalProgress {
                    current_value: current,
                    target_value: target,
                    percentage: pct,
                    display_text,
                }
            }
            GoalKind::Milestone { .. } => GoalProgress {
                current_value: 0.0,
                target_value: 1.0,
                percentage: 0.0,
                display_text: "In progress — mark complete when ready".to_string(),
            },
        };

        progress_map.insert(goal.id.clone(), progress);
    }

    progress_map
}

/// Build a human-readable label and machine type discriminant for a GoalKind.
fn goal_kind_label(kind: &GoalKind) -> (String, String) {
    match kind {
        GoalKind::SessionFrequency {
            target_days_per_week,
        } => (
            format!("Practise {target_days_per_week} days per week"),
            "session_frequency".to_string(),
        ),
        GoalKind::PracticeTime {
            target_minutes_per_week,
        } => (
            format!("Practise {target_minutes_per_week} minutes per week"),
            "practice_time".to_string(),
        ),
        GoalKind::ItemMastery { target_score, .. } => (
            format!("Reach score {target_score}"),
            "item_mastery".to_string(),
        ),
        GoalKind::Milestone { .. } => ("Milestone".to_string(), "milestone".to_string()),
    }
}

// ── Positive, process-focused encouragement text ─────────────────────

fn frequency_encouragement(pct: f64) -> &'static str {
    if pct >= 100.0 {
        "target reached! 🎯"
    } else if pct >= 60.0 {
        "great spacing for retention"
    } else if pct >= 30.0 {
        "building momentum"
    } else {
        "every session counts"
    }
}

fn time_encouragement(pct: f64) -> &'static str {
    if pct >= 100.0 {
        "target reached! 🎯"
    } else if pct >= 60.0 {
        "well on track"
    } else if pct >= 30.0 {
        "solid progress"
    } else {
        "every minute adds up"
    }
}

fn mastery_encouragement(pct: f64) -> &'static str {
    if pct >= 100.0 {
        "target reached! 🎯"
    } else if pct >= 75.0 {
        "nearly there"
    } else if pct >= 50.0 {
        "steady improvement"
    } else {
        "building foundations"
    }
}

fn apply_query_filter(items: Vec<LibraryItemView>, query: &ListQuery) -> Vec<LibraryItemView> {
    items
        .into_iter()
        .filter(|item| {
            // Filter by item type
            if let Some(ref item_type) = query.item_type {
                if item.item_type != item_type.to_string() {
                    return false;
                }
            }

            // Filter by key
            if let Some(ref key) = query.key {
                if item.key.as_deref() != Some(key.as_str()) {
                    return false;
                }
            }

            // Filter by category (exercises only)
            if let Some(ref category) = query.category {
                if item.category.as_deref() != Some(category.as_str()) {
                    return false;
                }
            }

            // Filter by tags (all must match, case-insensitive)
            if let Some(ref tags) = query.tags {
                for tag in tags {
                    let tag_lower = tag.to_lowercase();
                    if !item.tags.iter().any(|t| t.to_lowercase() == tag_lower) {
                        return false;
                    }
                }
            }

            // Filter by text search (case-insensitive substring match)
            if let Some(ref text) = query.text {
                let text_lower = text.to_lowercase();
                let matches = item.title.to_lowercase().contains(&text_lower)
                    || item.subtitle.to_lowercase().contains(&text_lower)
                    || item
                        .notes
                        .as_ref()
                        .is_some_and(|n| n.to_lowercase().contains(&text_lower))
                    || item
                        .tags
                        .iter()
                        .any(|t| t.to_lowercase().contains(&text_lower))
                    || item
                        .category
                        .as_ref()
                        .is_some_and(|c| c.to_lowercase().contains(&text_lower));
                if !matches {
                    return false;
                }
            }

            true
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_data_loaded_populates_model() {
        let app = Intrada;
        let mut model = Model::default();

        let now = chrono::Utc::now();
        let items = vec![
            Item {
                id: "piece1".to_string(),
                title: "Clair de Lune".to_string(),
                kind: ItemKind::Piece,
                composer: Some("Debussy".to_string()),
                category: None,
                key: Some("Db Major".to_string()),
                tempo: None,
                notes: None,
                tags: vec![],
                created_at: now,
                updated_at: now,
            },
            Item {
                id: "ex1".to_string(),
                title: "C Major Scale".to_string(),
                kind: ItemKind::Exercise,
                composer: None,
                category: Some("Scales".to_string()),
                key: Some("C Major".to_string()),
                tempo: None,
                notes: None,
                tags: vec![],
                created_at: now,
                updated_at: now,
            },
        ];

        let _cmd = app.update(Event::DataLoaded { items }, &mut model);

        assert_eq!(model.items.len(), 2);
        assert_eq!(model.items[0].title, "Clair de Lune");
        assert_eq!(model.items[1].title, "C Major Scale");
        assert!(model.last_error.is_none());
    }

    #[test]
    fn test_clear_error() {
        let app = Intrada;
        let mut model = Model {
            last_error: Some("some error".to_string()),
            ..Default::default()
        };

        let _cmd = app.update(Event::ClearError, &mut model);

        assert!(model.last_error.is_none());
    }

    #[test]
    fn test_view_empty_model() {
        let app = Intrada;
        let model = Model::default();
        let vm = app.view(&model);

        assert!(vm.items.is_empty());
        assert_eq!(vm.items.len(), 0);
        assert!(vm.error.is_none());
        assert_eq!(vm.session_status, "idle");
    }

    #[test]
    fn test_view_with_items() {
        let app = Intrada;
        let now = chrono::Utc::now();
        let model = Model {
            items: vec![
                Item {
                    id: "p1".to_string(),
                    title: "Sonata".to_string(),
                    kind: ItemKind::Piece,
                    composer: Some("Beethoven".to_string()),
                    category: None,
                    key: None,
                    tempo: Some(crate::domain::types::Tempo {
                        marking: Some("Allegro".to_string()),
                        bpm: Some(132),
                    }),
                    notes: None,
                    tags: vec!["classical".to_string()],
                    created_at: now,
                    updated_at: now,
                },
                Item {
                    id: "e1".to_string(),
                    title: "Scales".to_string(),
                    kind: ItemKind::Exercise,
                    composer: None,
                    category: Some("Technique".to_string()),
                    key: None,
                    tempo: None,
                    notes: None,
                    tags: vec![],
                    created_at: now,
                    updated_at: now,
                },
            ],
            ..Default::default()
        };

        let vm = app.view(&model);

        assert_eq!(vm.items.len(), 2);

        // Check piece
        let piece_view = vm.items.iter().find(|i| i.id == "p1").unwrap();
        assert_eq!(piece_view.item_type, "piece");
        assert_eq!(piece_view.title, "Sonata");
        assert_eq!(piece_view.subtitle, "Beethoven");
        assert_eq!(piece_view.tempo, Some("Allegro (132 BPM)".to_string()));
        assert_eq!(piece_view.tags, vec!["classical".to_string()]);

        // Check exercise
        let ex_view = vm.items.iter().find(|i| i.id == "e1").unwrap();
        assert_eq!(ex_view.item_type, "exercise");
        assert_eq!(ex_view.title, "Scales");
        assert_eq!(ex_view.subtitle, "Technique");
        assert_eq!(ex_view.category, Some("Technique".to_string()));
    }

    #[test]
    fn test_view_shows_error() {
        let app = Intrada;
        let model = Model {
            last_error: Some("Something went wrong".to_string()),
            ..Default::default()
        };

        let vm = app.view(&model);
        assert_eq!(vm.error, Some("Something went wrong".to_string()));
    }

    // --- Query filtering in core ---

    #[test]
    fn test_set_query_filters_by_type() {
        let app = Intrada;
        let mut model = Model::default();
        let now = chrono::Utc::now();

        model.items.push(Item {
            id: "p1".to_string(),
            title: "Sonata".to_string(),
            kind: ItemKind::Piece,
            composer: Some("Beethoven".to_string()),
            category: None,
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        });
        model.items.push(Item {
            id: "e1".to_string(),
            title: "Scales".to_string(),
            kind: ItemKind::Exercise,
            composer: None,
            category: Some("Technique".to_string()),
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        });

        // No filter — both items
        let vm = app.view(&model);
        assert_eq!(vm.items.len(), 2);

        // Filter to pieces only
        let _cmd = app.update(
            Event::SetQuery(Some(ListQuery {
                item_type: Some(ItemKind::Piece),
                ..Default::default()
            })),
            &mut model,
        );
        let vm = app.view(&model);
        assert_eq!(vm.items.len(), 1);
        assert_eq!(vm.items[0].item_type, "piece");

        // Clear filter
        let _cmd = app.update(Event::SetQuery(None), &mut model);
        let vm = app.view(&model);
        assert_eq!(vm.items.len(), 2);
    }

    #[test]
    fn test_set_query_filters_by_text() {
        let app = Intrada;
        let mut model = Model::default();
        let now = chrono::Utc::now();

        model.items.push(Item {
            id: "p1".to_string(),
            title: "Moonlight Sonata".to_string(),
            kind: ItemKind::Piece,
            composer: Some("Beethoven".to_string()),
            category: None,
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        });
        model.items.push(Item {
            id: "p2".to_string(),
            title: "Clair de Lune".to_string(),
            kind: ItemKind::Piece,
            composer: Some("Debussy".to_string()),
            category: None,
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        });

        model.active_query = Some(ListQuery {
            text: Some("beethoven".to_string()),
            ..Default::default()
        });

        let vm = app.view(&model);
        assert_eq!(vm.items.len(), 1);
        assert_eq!(vm.items[0].title, "Moonlight Sonata");
    }

    #[test]
    fn test_set_query_filters_by_category() {
        let app = Intrada;
        let mut model = Model::default();
        let now = chrono::Utc::now();

        model.items.push(Item {
            id: "e1".to_string(),
            title: "C Scale".to_string(),
            kind: ItemKind::Exercise,
            composer: Some("Hanon".to_string()),
            category: Some("Scales".to_string()),
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        });
        model.items.push(Item {
            id: "e2".to_string(),
            title: "Chord Inversions".to_string(),
            kind: ItemKind::Exercise,
            composer: None,
            category: Some("Chords".to_string()),
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        });

        model.active_query = Some(ListQuery {
            category: Some("Scales".to_string()),
            ..Default::default()
        });

        let vm = app.view(&model);
        assert_eq!(vm.items.len(), 1);
        assert_eq!(vm.items[0].title, "C Scale");
    }

    #[test]
    fn test_set_query_filters_by_tags() {
        let app = Intrada;
        let mut model = Model::default();
        let now = chrono::Utc::now();

        model.items.push(Item {
            id: "p1".to_string(),
            title: "Sonata".to_string(),
            kind: ItemKind::Piece,
            composer: Some("Beethoven".to_string()),
            category: None,
            key: None,
            tempo: None,
            notes: None,
            tags: vec!["classical".to_string(), "piano".to_string()],
            created_at: now,
            updated_at: now,
        });
        model.items.push(Item {
            id: "p2".to_string(),
            title: "Etude".to_string(),
            kind: ItemKind::Piece,
            composer: Some("Chopin".to_string()),
            category: None,
            key: None,
            tempo: None,
            notes: None,
            tags: vec!["romantic".to_string(), "piano".to_string()],
            created_at: now,
            updated_at: now,
        });

        model.active_query = Some(ListQuery {
            tags: Some(vec!["classical".to_string()]),
            ..Default::default()
        });

        let vm = app.view(&model);
        assert_eq!(vm.items.len(), 1);
        assert_eq!(vm.items[0].title, "Sonata");
    }

    // --- T042: Unicode handling in core ---

    #[test]
    fn test_unicode_in_item_add() {
        let app = Intrada;
        let mut model = Model::default();

        let _cmd = app.update(
            Event::Item(ItemEvent::Add(crate::domain::types::CreateItem {
                title: "Ménuet en Sol".to_string(),
                kind: ItemKind::Piece,
                composer: Some("Dvořák".to_string()),
                category: None,
                key: Some("ré mineur".to_string()),
                tempo: None,
                notes: Some("Pièce très jolie — «superbe»".to_string()),
                tags: vec!["日本語タグ".to_string()],
            })),
            &mut model,
        );

        assert!(model.last_error.is_none());
        assert_eq!(model.items.len(), 1);
        assert_eq!(model.items[0].title, "Ménuet en Sol");
        assert_eq!(model.items[0].composer, Some("Dvořák".to_string()));
        assert_eq!(model.items[0].key, Some("ré mineur".to_string()));
        assert_eq!(
            model.items[0].notes,
            Some("Pièce très jolie — «superbe»".to_string())
        );
        assert_eq!(model.items[0].tags, vec!["日本語タグ".to_string()]);

        // Verify ViewModel preserves Unicode
        let vm = app.view(&model);
        assert_eq!(vm.items[0].title, "Ménuet en Sol");
        assert_eq!(vm.items[0].subtitle, "Dvořák");
    }

    // --- T045: Performance benchmark ---

    #[test]
    fn test_performance_10k_items() {
        let app = Intrada;
        let mut model = Model::default();
        let now = chrono::Utc::now();

        // Populate 10,000 items (5k pieces + 5k exercises)
        let start = std::time::Instant::now();
        for i in 0..5000 {
            model.items.push(Item {
                id: format!("p{i:05}"),
                title: format!("Piece {i}"),
                kind: ItemKind::Piece,
                composer: Some(format!("Composer {}", i % 100)),
                category: None,
                key: if i % 3 == 0 {
                    Some("C Major".to_string())
                } else {
                    None
                },
                tempo: if i % 5 == 0 {
                    Some(crate::domain::types::Tempo {
                        marking: Some("Allegro".to_string()),
                        bpm: Some(120),
                    })
                } else {
                    None
                },
                notes: if i % 7 == 0 {
                    Some(format!("Notes for piece {i}"))
                } else {
                    None
                },
                tags: vec![format!("tag{}", i % 10)],
                created_at: now,
                updated_at: now,
            });
        }
        for i in 0..5000 {
            model.items.push(Item {
                id: format!("e{i:05}"),
                title: format!("Exercise {i}"),
                kind: ItemKind::Exercise,
                composer: None,
                category: Some(format!("Category {}", i % 20)),
                key: if i % 4 == 0 {
                    Some("G Major".to_string())
                } else {
                    None
                },
                tempo: None,
                notes: None,
                tags: vec![format!("etag{}", i % 10)],
                created_at: now,
                updated_at: now,
            });
        }
        let populate_time = start.elapsed();
        assert!(
            populate_time.as_millis() < 100,
            "Populating 10k items took {}ms (target: <100ms)",
            populate_time.as_millis()
        );

        // Populate 500 sessions with 5 entries each (2,500 entries total)
        use crate::domain::session::{
            CompletionStatus, EntryStatus, PracticeSession, SetlistEntry,
        };
        let start = std::time::Instant::now();
        for s in 0..500u32 {
            let entries: Vec<SetlistEntry> = (0..5u32)
                .map(|e| {
                    let item_idx = ((s * 5 + e) % 10_000) as usize;
                    let (item_id, item_title, item_type) = if item_idx < 5000 {
                        (
                            format!("p{item_idx:05}"),
                            format!("Piece {item_idx}"),
                            "piece".to_string(),
                        )
                    } else {
                        let idx = item_idx - 5000;
                        (
                            format!("e{idx:05}"),
                            format!("Exercise {idx}"),
                            "exercise".to_string(),
                        )
                    };
                    SetlistEntry {
                        id: format!("se{s:04}_{e}"),
                        item_id,
                        item_title,
                        item_type,
                        position: e as usize,
                        duration_secs: 300,
                        status: EntryStatus::Completed,
                        notes: None,
                        score: if e % 2 == 0 { Some(3) } else { None },
                        intention: None,
                        rep_target: None,
                        rep_count: None,
                        rep_target_reached: None,
                        rep_history: None,
                        planned_duration_secs: None,
                        achieved_tempo: if e % 3 == 0 { Some(120) } else { None },
                    }
                })
                .collect();
            model.sessions.push(PracticeSession {
                id: format!("sess{s:04}"),
                started_at: now - chrono::Duration::hours(s as i64 + 1),
                completed_at: now - chrono::Duration::hours(s as i64),
                total_duration_secs: 1500,
                completion_status: CompletionStatus::Completed,
                session_notes: None,
                session_intention: None,
                entries,
            });
        }
        model.practice_summaries = build_practice_summaries(&model.sessions);
        let session_populate_time = start.elapsed();
        assert!(
            session_populate_time.as_millis() < 200,
            "Populating 500 sessions + cache took {}ms (target: <200ms)",
            session_populate_time.as_millis()
        );

        // Benchmark: view() with 10k items + 500 sessions
        let start = std::time::Instant::now();
        let vm = app.view(&model);
        let view_time = start.elapsed();
        assert_eq!(vm.items.len(), 10_000);
        assert!(
            view_time.as_millis() < 200,
            "view() with 10k items took {}ms (target: <200ms)",
            view_time.as_millis()
        );

        // Benchmark: add one more item with 10k existing
        let start = std::time::Instant::now();
        let _cmd = app.update(
            Event::Item(ItemEvent::Add(crate::domain::types::CreateItem {
                title: "New Piece".to_string(),
                kind: ItemKind::Piece,
                composer: Some("New Composer".to_string()),
                category: None,
                key: None,
                tempo: None,
                notes: None,
                tags: vec![],
            })),
            &mut model,
        );
        let add_time = start.elapsed();
        assert_eq!(model.items.len(), 10_001);
        assert!(
            add_time.as_millis() < 100,
            "Adding item with 10k existing took {}ms (target: <100ms)",
            add_time.as_millis()
        );

        // Benchmark: delete item with 10k existing
        let start = std::time::Instant::now();
        let _cmd = app.update(
            Event::Item(ItemEvent::Delete {
                id: "p00042".to_string(),
            }),
            &mut model,
        );
        let delete_time = start.elapsed();
        assert_eq!(model.items.len(), 10_000);
        assert!(
            delete_time.as_millis() < 100,
            "Deleting item with 10k existing took {}ms (target: <100ms)",
            delete_time.as_millis()
        );
    }

    // --- Practice summary with new setlist sessions ---

    #[test]
    fn test_view_practice_summary_with_setlist_sessions() {
        let app = Intrada;
        let now = chrono::Utc::now();
        let mut model = Model::default();

        let p1 = Item {
            id: "p1".to_string(),
            title: "Sonata".to_string(),
            kind: ItemKind::Piece,
            composer: Some("Beethoven".to_string()),
            category: None,
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        };
        let p2 = Item {
            id: "p2".to_string(),
            title: "Etude".to_string(),
            kind: ItemKind::Piece,
            composer: Some("Chopin".to_string()),
            category: None,
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        };
        model.items = vec![p1, p2];

        // Create a completed session with two entries
        use crate::domain::session::{
            CompletionStatus, EntryStatus, PracticeSession, SetlistEntry,
        };
        model.sessions.push(PracticeSession {
            id: "sess1".to_string(),
            started_at: now - chrono::Duration::minutes(60),
            completed_at: now,
            total_duration_secs: 2700,
            completion_status: CompletionStatus::Completed,
            session_notes: None,
            session_intention: None,
            entries: vec![
                SetlistEntry {
                    id: "e1".to_string(),
                    item_id: "p1".to_string(),
                    item_title: "Sonata".to_string(),
                    item_type: "piece".to_string(),
                    position: 0,
                    duration_secs: 1800, // 30 min
                    status: EntryStatus::Completed,
                    notes: None,
                    score: None,
                    intention: None,
                    rep_target: None,
                    rep_count: None,
                    rep_target_reached: None,
                    rep_history: None,
                    planned_duration_secs: None,
                    achieved_tempo: None,
                },
                SetlistEntry {
                    id: "e2".to_string(),
                    item_id: "p1".to_string(),
                    item_title: "Sonata".to_string(),
                    item_type: "piece".to_string(),
                    position: 1,
                    duration_secs: 900, // 15 min
                    status: EntryStatus::Completed,
                    notes: None,
                    score: None,
                    intention: None,
                    rep_target: None,
                    rep_count: None,
                    rep_target_reached: None,
                    rep_history: None,
                    planned_duration_secs: None,
                    achieved_tempo: None,
                },
            ],
        });
        model.practice_summaries = build_practice_summaries(&model.sessions);

        let vm = app.view(&model);
        let p1_view = vm.items.iter().find(|i| i.id == "p1").unwrap();
        let p2_view = vm.items.iter().find(|i| i.id == "p2").unwrap();

        // p1 has 2 entries totalling 45 minutes, no scores, no tempo
        assert_eq!(
            p1_view.practice,
            Some(ItemPracticeSummary {
                session_count: 2,
                total_minutes: 45,
                latest_score: None,
                score_history: vec![],
                latest_tempo: None,
                tempo_history: vec![],
            })
        );
        // p2 has no entries
        assert_eq!(p2_view.practice, None);
    }

    // ── Score history tests (T019) ────────────────────────────────────

    #[test]
    fn test_score_history_multiple_sessions() {
        let app = Intrada;
        let now = chrono::Utc::now();
        let mut model = Model::default();

        model.items.push(Item {
            id: "p1".to_string(),
            title: "Sonata".to_string(),
            kind: ItemKind::Piece,
            composer: Some("Beethoven".to_string()),
            category: None,
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        });

        use crate::domain::session::{
            CompletionStatus, EntryStatus, PracticeSession, SetlistEntry,
        };

        // Session 1: older, score 3
        model.sessions.push(PracticeSession {
            id: "sess1".to_string(),
            started_at: now - chrono::Duration::hours(2),
            completed_at: now - chrono::Duration::hours(1),
            total_duration_secs: 3600,
            completion_status: CompletionStatus::Completed,
            session_notes: None,
            session_intention: None,
            entries: vec![SetlistEntry {
                id: "e1".to_string(),
                item_id: "p1".to_string(),
                item_title: "Sonata".to_string(),
                item_type: "piece".to_string(),
                position: 0,
                duration_secs: 1800,
                status: EntryStatus::Completed,
                notes: None,
                score: Some(3),
                intention: None,
                rep_target: None,
                rep_count: None,
                rep_target_reached: None,
                rep_history: None,
                planned_duration_secs: None,
                achieved_tempo: None,
            }],
        });

        // Session 2: newer, score 5
        model.sessions.push(PracticeSession {
            id: "sess2".to_string(),
            started_at: now - chrono::Duration::minutes(30),
            completed_at: now,
            total_duration_secs: 1800,
            completion_status: CompletionStatus::Completed,
            session_notes: None,
            session_intention: None,
            entries: vec![SetlistEntry {
                id: "e2".to_string(),
                item_id: "p1".to_string(),
                item_title: "Sonata".to_string(),
                item_type: "piece".to_string(),
                position: 0,
                duration_secs: 900,
                status: EntryStatus::Completed,
                notes: None,
                score: Some(5),
                intention: None,
                rep_target: None,
                rep_count: None,
                rep_target_reached: None,
                rep_history: None,
                planned_duration_secs: None,
                achieved_tempo: None,
            }],
        });

        model.practice_summaries = build_practice_summaries(&model.sessions);
        let vm = app.view(&model);
        let p1 = vm.items.iter().find(|i| i.id == "p1").unwrap();
        let practice = p1.practice.as_ref().unwrap();

        // latest_score should be from the newer session
        assert_eq!(practice.latest_score, Some(5));
        assert_eq!(practice.score_history.len(), 2);
        // First entry = most recent (score 5)
        assert_eq!(practice.score_history[0].score, 5);
        assert_eq!(practice.score_history[0].session_id, "sess2");
        // Second entry = older (score 3)
        assert_eq!(practice.score_history[1].score, 3);
        assert_eq!(practice.score_history[1].session_id, "sess1");
    }

    #[test]
    fn test_score_history_no_scored_sessions() {
        let app = Intrada;
        let now = chrono::Utc::now();
        let mut model = Model::default();

        model.items.push(Item {
            id: "p1".to_string(),
            title: "Sonata".to_string(),
            kind: ItemKind::Piece,
            composer: Some("Beethoven".to_string()),
            category: None,
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        });

        use crate::domain::session::{
            CompletionStatus, EntryStatus, PracticeSession, SetlistEntry,
        };

        // Session with no score
        model.sessions.push(PracticeSession {
            id: "sess1".to_string(),
            started_at: now - chrono::Duration::hours(1),
            completed_at: now,
            total_duration_secs: 1800,
            completion_status: CompletionStatus::Completed,
            session_notes: None,
            session_intention: None,
            entries: vec![SetlistEntry {
                id: "e1".to_string(),
                item_id: "p1".to_string(),
                item_title: "Sonata".to_string(),
                item_type: "piece".to_string(),
                position: 0,
                duration_secs: 1800,
                status: EntryStatus::Completed,
                notes: None,
                score: None,
                intention: None,
                rep_target: None,
                rep_count: None,
                rep_target_reached: None,
                rep_history: None,
                planned_duration_secs: None,
                achieved_tempo: None,
            }],
        });

        model.practice_summaries = build_practice_summaries(&model.sessions);
        let vm = app.view(&model);
        let p1 = vm.items.iter().find(|i| i.id == "p1").unwrap();
        let practice = p1.practice.as_ref().unwrap();

        assert_eq!(practice.latest_score, None);
        assert!(practice.score_history.is_empty());
    }

    #[test]
    fn test_score_history_item_multiple_times_in_one_session() {
        let app = Intrada;
        let now = chrono::Utc::now();
        let mut model = Model::default();

        model.items.push(Item {
            id: "p1".to_string(),
            title: "Sonata".to_string(),
            kind: ItemKind::Piece,
            composer: Some("Beethoven".to_string()),
            category: None,
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        });

        use crate::domain::session::{
            CompletionStatus, EntryStatus, PracticeSession, SetlistEntry,
        };

        // Single session with the same item twice (different scores)
        model.sessions.push(PracticeSession {
            id: "sess1".to_string(),
            started_at: now - chrono::Duration::hours(1),
            completed_at: now,
            total_duration_secs: 3600,
            completion_status: CompletionStatus::Completed,
            session_notes: None,
            session_intention: None,
            entries: vec![
                SetlistEntry {
                    id: "e1".to_string(),
                    item_id: "p1".to_string(),
                    item_title: "Sonata".to_string(),
                    item_type: "piece".to_string(),
                    position: 0,
                    duration_secs: 1800,
                    status: EntryStatus::Completed,
                    notes: None,
                    score: Some(2),
                    intention: None,
                    rep_target: None,
                    rep_count: None,
                    rep_target_reached: None,
                    rep_history: None,
                    planned_duration_secs: None,
                    achieved_tempo: None,
                },
                SetlistEntry {
                    id: "e2".to_string(),
                    item_id: "p1".to_string(),
                    item_title: "Sonata".to_string(),
                    item_type: "piece".to_string(),
                    position: 1,
                    duration_secs: 1800,
                    status: EntryStatus::Completed,
                    notes: None,
                    score: Some(4),
                    intention: None,
                    rep_target: None,
                    rep_count: None,
                    rep_target_reached: None,
                    rep_history: None,
                    planned_duration_secs: None,
                    achieved_tempo: None,
                },
            ],
        });

        model.practice_summaries = build_practice_summaries(&model.sessions);
        let vm = app.view(&model);
        let p1 = vm.items.iter().find(|i| i.id == "p1").unwrap();
        let practice = p1.practice.as_ref().unwrap();

        // Both entries from the same session should appear in score_history
        assert_eq!(practice.score_history.len(), 2);
        // Both have the same session_id
        assert!(practice
            .score_history
            .iter()
            .all(|e| e.session_id == "sess1"));
    }

    #[test]
    fn test_score_history_skipped_entries_excluded() {
        let app = Intrada;
        let now = chrono::Utc::now();
        let mut model = Model::default();

        model.items.push(Item {
            id: "p1".to_string(),
            title: "Sonata".to_string(),
            kind: ItemKind::Piece,
            composer: Some("Beethoven".to_string()),
            category: None,
            key: None,
            tempo: None,
            notes: None,
            tags: vec![],
            created_at: now,
            updated_at: now,
        });

        use crate::domain::session::{
            CompletionStatus, EntryStatus, PracticeSession, SetlistEntry,
        };

        // A skipped entry won't have a score (scores only set on completed entries)
        model.sessions.push(PracticeSession {
            id: "sess1".to_string(),
            started_at: now - chrono::Duration::hours(1),
            completed_at: now,
            total_duration_secs: 600,
            completion_status: CompletionStatus::EndedEarly,
            session_notes: None,
            session_intention: None,
            entries: vec![SetlistEntry {
                id: "e1".to_string(),
                item_id: "p1".to_string(),
                item_title: "Sonata".to_string(),
                item_type: "piece".to_string(),
                position: 0,
                duration_secs: 600,
                status: EntryStatus::Skipped,
                notes: None,
                score: None, // Skipped entries never have scores
                intention: None,
                rep_target: None,
                rep_count: None,
                rep_target_reached: None,
                rep_history: None,
                planned_duration_secs: None,
                achieved_tempo: None,
            }],
        });

        model.practice_summaries = build_practice_summaries(&model.sessions);
        let vm = app.view(&model);
        let p1 = vm.items.iter().find(|i| i.id == "p1").unwrap();
        let practice = p1.practice.as_ref().unwrap();

        assert_eq!(practice.latest_score, None);
        assert!(practice.score_history.is_empty());
    }

    #[test]
    fn test_view_empty_sessions() {
        let app = Intrada;
        let model = Model::default();
        let vm = app.view(&model);
        assert!(vm.sessions.is_empty());
    }

    #[test]
    fn test_tempo_format_display() {
        use crate::domain::types::Tempo;

        // None tempo — map returns None
        let none_tempo: Option<Tempo> = None;
        assert_eq!(none_tempo.as_ref().map(|t| t.format_display()), None);

        // Both None — empty string
        let tempo = Tempo {
            marking: None,
            bpm: None,
        };
        assert_eq!(tempo.format_display(), "");

        // Marking only
        let tempo = Tempo {
            marking: Some("Adagio".to_string()),
            bpm: None,
        };
        assert_eq!(tempo.format_display(), "Adagio");

        // BPM only
        let tempo = Tempo {
            marking: None,
            bpm: Some(120),
        };
        assert_eq!(tempo.format_display(), "120 BPM");

        // Both
        let tempo = Tempo {
            marking: Some("Allegro".to_string()),
            bpm: Some(132),
        };
        assert_eq!(tempo.format_display(), "Allegro (132 BPM)");
    }

    // ── Goal event handler tests (T010) ──────────────────────────────

    fn make_test_goal(id: &str, kind: GoalKind, status: GoalStatus) -> Goal {
        let now = chrono::Utc::now();
        Goal {
            id: id.to_string(),
            title: format!("Goal {id}"),
            kind,
            status,
            deadline: None,
            created_at: now,
            updated_at: now,
            completed_at: None,
        }
    }

    #[test]
    fn test_goal_add_creates_goal() {
        let app = Intrada;
        let mut model = Model::default();
        let _cmd = app.update(
            Event::Goal(GoalEvent::Add(crate::domain::types::CreateGoal {
                title: "Practise 5 days per week".to_string(),
                kind: GoalKind::SessionFrequency {
                    target_days_per_week: 5,
                },
                deadline: None,
            })),
            &mut model,
        );
        assert!(model.last_error.is_none());
        assert_eq!(model.goals.len(), 1);
        assert_eq!(model.goals[0].title, "Practise 5 days per week");
        assert_eq!(model.goals[0].status, GoalStatus::Active);
        assert!(model.goals[0].completed_at.is_none());
    }

    #[test]
    fn test_goal_add_validation_error() {
        let app = Intrada;
        let mut model = Model::default();
        let _cmd = app.update(
            Event::Goal(GoalEvent::Add(crate::domain::types::CreateGoal {
                title: "".to_string(),
                kind: GoalKind::SessionFrequency {
                    target_days_per_week: 5,
                },
                deadline: None,
            })),
            &mut model,
        );
        assert!(model.last_error.is_some());
        assert_eq!(model.goals.len(), 0);
    }

    #[test]
    fn test_goal_complete_active_goal() {
        let app = Intrada;
        let mut model = Model::default();
        model.goals.push(make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 3,
            },
            GoalStatus::Active,
        ));

        let _cmd = app.update(
            Event::Goal(GoalEvent::Complete {
                id: "g1".to_string(),
            }),
            &mut model,
        );

        assert!(model.last_error.is_none());
        assert_eq!(model.goals[0].status, GoalStatus::Completed);
        assert!(model.goals[0].completed_at.is_some());
    }

    #[test]
    fn test_goal_complete_archived_goal_rejected() {
        let app = Intrada;
        let mut model = Model::default();
        model.goals.push(make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 3,
            },
            GoalStatus::Archived,
        ));

        let _cmd = app.update(
            Event::Goal(GoalEvent::Complete {
                id: "g1".to_string(),
            }),
            &mut model,
        );

        assert!(model.last_error.is_some());
        assert_eq!(model.goals[0].status, GoalStatus::Archived);
    }

    #[test]
    fn test_goal_archive_active_goal() {
        let app = Intrada;
        let mut model = Model::default();
        model.goals.push(make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 3,
            },
            GoalStatus::Active,
        ));

        let _cmd = app.update(
            Event::Goal(GoalEvent::Archive {
                id: "g1".to_string(),
            }),
            &mut model,
        );

        assert!(model.last_error.is_none());
        assert_eq!(model.goals[0].status, GoalStatus::Archived);
    }

    #[test]
    fn test_goal_archive_completed_goal_rejected() {
        let app = Intrada;
        let mut model = Model::default();
        let mut goal = make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 3,
            },
            GoalStatus::Completed,
        );
        goal.completed_at = Some(chrono::Utc::now());
        model.goals.push(goal);

        let _cmd = app.update(
            Event::Goal(GoalEvent::Archive {
                id: "g1".to_string(),
            }),
            &mut model,
        );

        assert!(model.last_error.is_some());
        assert_eq!(model.goals[0].status, GoalStatus::Completed);
    }

    #[test]
    fn test_goal_reactivate_archived_goal() {
        let app = Intrada;
        let mut model = Model::default();
        model.goals.push(make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 3,
            },
            GoalStatus::Archived,
        ));

        let _cmd = app.update(
            Event::Goal(GoalEvent::Reactivate {
                id: "g1".to_string(),
            }),
            &mut model,
        );

        assert!(model.last_error.is_none());
        assert_eq!(model.goals[0].status, GoalStatus::Active);
    }

    #[test]
    fn test_goal_reactivate_active_goal_rejected() {
        let app = Intrada;
        let mut model = Model::default();
        model.goals.push(make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 3,
            },
            GoalStatus::Active,
        ));

        let _cmd = app.update(
            Event::Goal(GoalEvent::Reactivate {
                id: "g1".to_string(),
            }),
            &mut model,
        );

        assert!(model.last_error.is_some());
        assert_eq!(model.goals[0].status, GoalStatus::Active);
    }

    #[test]
    fn test_goal_delete() {
        let app = Intrada;
        let mut model = Model::default();
        model.goals.push(make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 3,
            },
            GoalStatus::Active,
        ));

        let _cmd = app.update(
            Event::Goal(GoalEvent::Delete {
                id: "g1".to_string(),
            }),
            &mut model,
        );

        assert!(model.last_error.is_none());
        assert_eq!(model.goals.len(), 0);
    }

    #[test]
    fn test_goal_delete_not_found() {
        let app = Intrada;
        let mut model = Model::default();

        let _cmd = app.update(
            Event::Goal(GoalEvent::Delete {
                id: "nonexistent".to_string(),
            }),
            &mut model,
        );

        assert!(model.last_error.is_some());
    }

    #[test]
    fn test_goal_update_title() {
        let app = Intrada;
        let mut model = Model::default();
        model.goals.push(make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 5,
            },
            GoalStatus::Active,
        ));

        let _cmd = app.update(
            Event::Goal(GoalEvent::Update {
                id: "g1".to_string(),
                input: crate::domain::types::UpdateGoal {
                    title: Some("Updated title".to_string()),
                    ..Default::default()
                },
            }),
            &mut model,
        );

        assert!(model.last_error.is_none());
        assert_eq!(model.goals[0].title, "Updated title");
    }

    #[test]
    fn test_goals_loaded_populates_model() {
        let app = Intrada;
        let mut model = Model::default();
        let goals = vec![
            make_test_goal(
                "g1",
                GoalKind::SessionFrequency {
                    target_days_per_week: 5,
                },
                GoalStatus::Active,
            ),
            make_test_goal(
                "g2",
                GoalKind::Milestone {
                    description: "Learn Bach".to_string(),
                },
                GoalStatus::Active,
            ),
        ];

        let _cmd = app.update(Event::GoalsLoaded { goals }, &mut model);

        assert_eq!(model.goals.len(), 2);
    }

    // ── Goal view tests ──────────────────────────────────────────────

    #[test]
    fn test_view_goals_in_viewmodel() {
        let app = Intrada;
        let mut model = Model::default();
        model.goals.push(make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 5,
            },
            GoalStatus::Active,
        ));
        model.goals.push(make_test_goal(
            "g2",
            GoalKind::Milestone {
                description: "Learn Bach".to_string(),
            },
            GoalStatus::Completed,
        ));

        let vm = app.view(&model);

        assert_eq!(vm.goals.len(), 2);
        let g1 = vm.goals.iter().find(|g| g.id == "g1").unwrap();
        assert_eq!(g1.kind_type, "session_frequency");
        assert_eq!(g1.status, "active");
        assert!(g1.progress.is_some()); // Active goals get progress

        let g2 = vm.goals.iter().find(|g| g.id == "g2").unwrap();
        assert_eq!(g2.kind_type, "milestone");
        assert_eq!(g2.status, "completed");
        assert!(g2.progress.is_none()); // Completed goals don't get progress
    }

    // ── compute_goal_progress tests (T011) ───────────────────────────

    fn make_session_at(
        id: &str,
        started_at: chrono::DateTime<chrono::Utc>,
        duration_secs: u64,
    ) -> PracticeSession {
        use crate::domain::session::CompletionStatus;
        PracticeSession {
            id: id.to_string(),
            started_at,
            completed_at: started_at + chrono::Duration::seconds(duration_secs as i64),
            total_duration_secs: duration_secs,
            completion_status: CompletionStatus::Completed,
            session_notes: None,
            session_intention: None,
            entries: vec![],
        }
    }

    /// Helper: create a DateTime<Utc> from a NaiveDate at noon UTC.
    fn date_to_utc(date: chrono::NaiveDate) -> chrono::DateTime<chrono::Utc> {
        date.and_hms_opt(12, 0, 0).unwrap().and_utc()
    }

    #[test]
    fn test_progress_frequency_no_sessions() {
        let now = chrono::Utc::now();
        let goals = vec![make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 5,
            },
            GoalStatus::Active,
        )];

        let result = compute_goal_progress(&goals, &[], &std::collections::HashMap::new(), now);

        let p = result.get("g1").unwrap();
        assert_eq!(p.current_value, 0.0);
        assert_eq!(p.target_value, 5.0);
        assert_eq!(p.percentage, 0.0);
        assert!(p.display_text.contains("Start your first session"));
    }

    #[test]
    fn test_progress_frequency_partial_sessions() {
        use chrono::{Datelike, NaiveDate};

        // Pick a Wednesday to ensure it's mid-week
        let today = NaiveDate::from_ymd_opt(2026, 2, 25).unwrap(); // Wednesday
        let now = date_to_utc(today);

        // Sessions on Monday and Tuesday of same week
        let iso = today.iso_week();
        let monday =
            NaiveDate::from_isoywd_opt(iso.year(), iso.week(), chrono::Weekday::Mon).unwrap();
        let tuesday = monday + chrono::Duration::days(1);

        let sessions = vec![
            make_session_at("s1", date_to_utc(monday), 1800),
            make_session_at("s2", date_to_utc(tuesday), 2400),
        ];

        let goals = vec![make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 5,
            },
            GoalStatus::Active,
        )];

        let result =
            compute_goal_progress(&goals, &sessions, &std::collections::HashMap::new(), now);

        let p = result.get("g1").unwrap();
        assert_eq!(p.current_value, 2.0);
        assert_eq!(p.target_value, 5.0);
        assert!((p.percentage - 40.0).abs() < 0.01);
        assert!(p.display_text.contains("2 of 5 days"));
    }

    #[test]
    fn test_progress_frequency_target_reached() {
        use chrono::{Datelike, NaiveDate};

        let today = NaiveDate::from_ymd_opt(2026, 2, 27).unwrap(); // Friday
        let now = date_to_utc(today);

        let iso = today.iso_week();
        let monday =
            NaiveDate::from_isoywd_opt(iso.year(), iso.week(), chrono::Weekday::Mon).unwrap();

        // Sessions every day Mon-Fri (5 days, target is 5)
        let sessions: Vec<PracticeSession> = (0..5)
            .map(|i| {
                let day = monday + chrono::Duration::days(i);
                make_session_at(&format!("s{i}"), date_to_utc(day), 1800)
            })
            .collect();

        let goals = vec![make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 5,
            },
            GoalStatus::Active,
        )];

        let result =
            compute_goal_progress(&goals, &sessions, &std::collections::HashMap::new(), now);

        let p = result.get("g1").unwrap();
        assert_eq!(p.percentage, 100.0);
        assert!(p.display_text.contains("target reached"));
    }

    #[test]
    fn test_progress_frequency_capped_at_100() {
        use chrono::{Datelike, NaiveDate};

        let today = NaiveDate::from_ymd_opt(2026, 2, 28).unwrap(); // Saturday
        let now = date_to_utc(today);

        let iso = today.iso_week();
        let monday =
            NaiveDate::from_isoywd_opt(iso.year(), iso.week(), chrono::Weekday::Mon).unwrap();

        // Sessions every day Mon-Sat (6 days, target is 3)
        let sessions: Vec<PracticeSession> = (0..6)
            .map(|i| {
                let day = monday + chrono::Duration::days(i);
                make_session_at(&format!("s{i}"), date_to_utc(day), 1800)
            })
            .collect();

        let goals = vec![make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 3,
            },
            GoalStatus::Active,
        )];

        let result =
            compute_goal_progress(&goals, &sessions, &std::collections::HashMap::new(), now);

        let p = result.get("g1").unwrap();
        assert_eq!(p.percentage, 100.0); // Capped, not 200%
    }

    #[test]
    fn test_progress_frequency_last_week_excluded() {
        use chrono::NaiveDate;

        let today = NaiveDate::from_ymd_opt(2026, 2, 25).unwrap(); // Wednesday
        let now = date_to_utc(today);

        // Session from last week (should not count)
        let last_week = today - chrono::Duration::days(7);
        let sessions = vec![make_session_at("s1", date_to_utc(last_week), 3600)];

        let goals = vec![make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 5,
            },
            GoalStatus::Active,
        )];

        let result =
            compute_goal_progress(&goals, &sessions, &std::collections::HashMap::new(), now);

        let p = result.get("g1").unwrap();
        assert_eq!(p.current_value, 0.0);
        assert!(p.display_text.contains("Start your first session"));
    }

    #[test]
    fn test_progress_time_partial() {
        use chrono::{Datelike, NaiveDate};

        let today = NaiveDate::from_ymd_opt(2026, 2, 25).unwrap();
        let now = date_to_utc(today);

        let iso = today.iso_week();
        let monday =
            NaiveDate::from_isoywd_opt(iso.year(), iso.week(), chrono::Weekday::Mon).unwrap();

        // 45 min on Monday + 30 min on Tuesday = 75 min total
        let sessions = vec![
            make_session_at("s1", date_to_utc(monday), 2700), // 45 min
            make_session_at("s2", date_to_utc(monday + chrono::Duration::days(1)), 1800), // 30 min
        ];

        let goals = vec![make_test_goal(
            "g1",
            GoalKind::PracticeTime {
                target_minutes_per_week: 120,
            },
            GoalStatus::Active,
        )];

        let result =
            compute_goal_progress(&goals, &sessions, &std::collections::HashMap::new(), now);

        let p = result.get("g1").unwrap();
        assert_eq!(p.current_value, 75.0);
        assert_eq!(p.target_value, 120.0);
        assert!(p.display_text.contains("75 of 120 min"));
    }

    #[test]
    fn test_progress_time_no_sessions() {
        let now = chrono::Utc::now();
        let goals = vec![make_test_goal(
            "g1",
            GoalKind::PracticeTime {
                target_minutes_per_week: 120,
            },
            GoalStatus::Active,
        )];

        let result = compute_goal_progress(&goals, &[], &std::collections::HashMap::new(), now);

        let p = result.get("g1").unwrap();
        assert_eq!(p.current_value, 0.0);
        assert!(p.display_text.contains("Start your first session"));
    }

    #[test]
    fn test_progress_mastery_with_score() {
        let now = chrono::Utc::now();
        let goals = vec![make_test_goal(
            "g1",
            GoalKind::ItemMastery {
                item_id: "item-1".to_string(),
                target_score: 4,
            },
            GoalStatus::Active,
        )];

        let mut summaries = std::collections::HashMap::new();
        summaries.insert(
            "item-1".to_string(),
            ItemPracticeSummary {
                session_count: 3,
                total_minutes: 90,
                latest_score: Some(3),
                score_history: vec![],
                latest_tempo: None,
                tempo_history: vec![],
            },
        );

        let result = compute_goal_progress(&goals, &[], &summaries, now);

        let p = result.get("g1").unwrap();
        assert_eq!(p.current_value, 3.0);
        assert_eq!(p.target_value, 4.0);
        assert!((p.percentage - 75.0).abs() < 0.01);
        assert!(p.display_text.contains("Score 3 of 4"));
    }

    #[test]
    fn test_progress_mastery_no_score() {
        let now = chrono::Utc::now();
        let goals = vec![make_test_goal(
            "g1",
            GoalKind::ItemMastery {
                item_id: "item-1".to_string(),
                target_score: 4,
            },
            GoalStatus::Active,
        )];

        let result = compute_goal_progress(&goals, &[], &std::collections::HashMap::new(), now);

        let p = result.get("g1").unwrap();
        assert_eq!(p.current_value, 0.0);
        assert_eq!(p.percentage, 0.0);
        assert!(p.display_text.contains("No score recorded"));
    }

    #[test]
    fn test_progress_milestone_active() {
        let now = chrono::Utc::now();
        let goals = vec![make_test_goal(
            "g1",
            GoalKind::Milestone {
                description: "Memorise first movement".to_string(),
            },
            GoalStatus::Active,
        )];

        let result = compute_goal_progress(&goals, &[], &std::collections::HashMap::new(), now);

        let p = result.get("g1").unwrap();
        assert_eq!(p.percentage, 0.0);
        assert!(p.display_text.contains("In progress"));
    }

    #[test]
    fn test_progress_completed_goal_excluded() {
        let now = chrono::Utc::now();
        let mut goal = make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 5,
            },
            GoalStatus::Completed,
        );
        goal.completed_at = Some(now);

        let result = compute_goal_progress(&[goal], &[], &std::collections::HashMap::new(), now);

        // Completed goals should not have progress computed
        assert!(!result.contains_key("g1"));
    }

    #[test]
    fn test_progress_archived_goal_excluded() {
        let now = chrono::Utc::now();
        let goals = vec![make_test_goal(
            "g1",
            GoalKind::SessionFrequency {
                target_days_per_week: 5,
            },
            GoalStatus::Archived,
        )];

        let result = compute_goal_progress(&goals, &[], &std::collections::HashMap::new(), now);

        assert!(!result.contains_key("g1"));
    }
}
