name: Build and Deploy Leptos Page

defaults:
  run:
    working-directory: ./web-leptos


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 'stable'
      - name: Build with Trunk
        run: trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist