name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
      working-directory: ./web-leptos

    - name: Install Trunk
      run: cargo install trunk
      working-directory: ./web-leptos

    - name: Build Leptos app
      run: trunk build --release
      working-directory: ./web-leptos

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web-leptos/dist
