name: Release to GitHub Pages

defaults:
  run:
    working-directory: ./web-leptos

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Github-Pages-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build with Trunk
        run: trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          folder: dist
